import Head from "next/head";
import Nav from "../components/Nav";

// import Image from 'next/image'

export default function Home() {
  return (
    <div className="bg-cove-bg-image bg-cover bg-center h-screen">
      <Head>
        <title>William Wright | Full-Stack Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />

      <div className="grid justify-items-center">
        <h1 className="text-dark-blue text-5xl pt-60">William W. Wright</h1>
        <h3 className="text-cool-grey text-2xl pt-3">
          Experience Architect // Full-Stack Web Developer
        </h3>
      </div>
    </div>
  );
}
